services:
  # Backend API Service
  - type: web
    name: ai-trading-bot-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: LICENSE_ENCRYPTION_KEY
        generateValue: true
    healthCheckPath: /api/health
    
  # Frontend Client Service
  - type: web
    name: ai-trading-bot-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-trading-bot-backend.onrender.com
        
databases:
  # MongoDB Atlas (external)
  # You'll need to provide MONGODB_URI in environment variables